# Generated by Django 5.2.4 on 2025-07-24 19:44

import django.db.models.deletion

from django.db import migrations, models

import scans.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=scans.models.generate_uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", scans.models.DateTimeUTCField(auto_now_add=True)),
                ("updated_at", scans.models.DateTimeUTCField(auto_now=True)),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=scans.models.generate_uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", scans.models.DateTimeUTCField(auto_now_add=True)),
                ("updated_at", scans.models.DateTimeUTCField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="checks", to="scans.provider"
                    ),
                ),
            ],
            options={
                "ordering": ["provider__name", "name"],
                "unique_together": {("provider", "name")},
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=scans.models.generate_uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", scans.models.DateTimeUTCField(auto_now_add=True)),
                ("updated_at", scans.models.DateTimeUTCField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", scans.models.DateTimeUTCField(blank=True, null=True)),
                ("finished_at", scans.models.DateTimeUTCField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scans", to="scans.provider"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=scans.models.generate_uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", scans.models.DateTimeUTCField(auto_now_add=True)),
                ("updated_at", scans.models.DateTimeUTCField(auto_now=True)),
                ("success", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "check_parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="scans.check",
                        verbose_name="check",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="findings", to="scans.scan"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("scan", "check_parent")},
            },
        ),
    ]
