# Common configurations using YAML anchors
x-common-app: &common-app
  image: prowler-manager/api:${ENVIRONMENT}
  env_file: .env
  volumes:
    - ./:/app/
  restart: unless-stopped

x-common-app-depends-postgres: &common-app-depends-postgres
  <<: *common-app
  depends_on:
    - postgres

services:

  api:
    <<: *common-app-depends-postgres
    build:
      context: .
      platforms:
        - "linux/amd64"
      args:
        ENVIRONMENT: ${ENVIRONMENT:-production}
        PYTHONHASHSEED: ${PYTHONHASHSEED:-42}
        PYTHON_IMAGE: ${PYTHON_IMAGE:-python:3.13.5-alpine3.22}
        UV_IMAGE: ${UV_IMAGE:-ghcr.io/astral-sh/uv:0.8.2-python3.13-alpine}
    container_name: prowler-manager-api
    ports:
      - ${API_PORT}:${API_PORT}

  worker:
    <<: *common-app-depends-postgres
    container_name: prowler-manager-worker
    command: worker

  debug:
    <<: *common-app-depends-postgres
    container_name: prowler-manager-debug
    ports:
      - ${API_PORT}:${API_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    command: debug

  test:
    <<: *common-app
    container_name: prowler-manager-test
    command: test
    restart: no

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:17.5-alpine3.22}
    container_name: prowler-manager-postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres_data:
