# Common configurations using YAML anchors
x-common-app: &common-app
  image: prowler-manager/api:${ENVIRONMENT}
  env_file: .env
  volumes:
    - ./:/app/
  restart: unless-stopped

x-common-app-depends-postgres: &common-app-depends-postgres
  <<: *common-app
  depends_on:
    - postgres

services:

  api:
    <<: *common-app-depends-postgres
    build:
      context: .
      platforms:
        - "linux/amd64"
      args:
        ENVIRONMENT: ${ENVIRONMENT:-production}
        PYTHONHASHSEED: ${PYTHONHASHSEED:-42}
        PYTHON_IMAGE: ${PYTHON_IMAGE:-python:3.13.5-alpine3.22}
        UV_IMAGE: ${UV_IMAGE:-ghcr.io/astral-sh/uv:0.8.2-python3.13-alpine}
    container_name: prowler-manager-api
    ports:
      - ${API_PORT}:${API_PORT}
    healthcheck:
      test: wget --quiet --tries=1 --spider http://127.0.0.1:${API_PORT}/api/health || exit 1
      interval: 15s
      timeout: 10s
      start_period: 3s

  worker:
    <<: *common-app-depends-postgres
    container_name: prowler-manager-worker
    healthcheck:
      test: python manage.py procrastinate healthchecks > /dev/null 2>&1 || exit 1
      interval: 15s
      timeout: 10s
      start_period: 3s
    command: worker

  debug-api:
    <<: *common-app-depends-postgres
    container_name: prowler-manager-debug-api
    ports:
      - ${API_PORT}:${API_PORT}
      - ${DEBUG_API_PORT}:${DEBUG_API_PORT}
    command: debug-api

  debug-worker:
    <<: *common-app-depends-postgres
    container_name: prowler-manager-debug-worker
    ports:
      - ${DEBUG_WORKER_PORT}:${DEBUG_WORKER_PORT}
    command: debug-worker

  test:
    <<: *common-app
    container_name: prowler-manager-test
    command: test
    restart: no

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:17.5-alpine3.22}
    container_name: prowler-manager-postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -q
      interval: 15s
      timeout: 10s
      start_period: 3s
    restart: unless-stopped

volumes:
  postgres_data:
