services:
  api:
    image: prowler-manager/api:${ENVIRONMENT}
    platform: linux/amd64
    build:
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT:-production}
        PYTHONHASHSEED: ${PYTHONHASHSEED:-42}
        PYTHON_IMAGE: ${PYTHON_IMAGE:-python:3.13.5-alpine3.22}
        UV_IMAGE: ${UV_IMAGE:-ghcr.io/astral-sh/uv:0.8.2-python3.13-alpine}
    container_name: prowler-manager-api
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./:/app/
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:17.5-alpine3.22
    container_name: prowler-manager-postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres_data:
